services:
  chatbot:
    build: .
    container_name: bot-norbridge-server
    restart: always
    # El usuario 1000 es el estándar de la imagen de Node y suele coincidir con tu usuario tic
    user: "1000:1000" 
    privileged: true
    ports:
      - "4001:4001"
    volumes:
      - ./.wwebjs_auth:/app/.wwebjs_auth
      - ./.env:/app/.env
    shm_size: '2gb'
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
