services:
  db:
    image: postgres:16-alpine
    container_name: bot-norbridge-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  chatbot:
    build: .
    container_name: bot-norbridge-server
    restart: always
    user: "1000:1000" 
    privileged: true
    ports:
      - "4001:4001"
    volumes:
      - ./.wwebjs_auth:/app/.wwebjs_auth
      - ./.env:/app/.env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - TZ=America/Argentina/Buenos_Aires
    shm_size: '2gb'
    depends_on:
      db:
        condition: service_healthy
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  pgdata:
